# Magic constants -- NEED TO MANUALLY KEEP UPDATED TO MATCH C MODULE
GAME_WIDTH = 160
GAME_HEIGHT = 128
SPECIAL_EVENT_SCORE_UP = 0
SPECIAL_EVENT_SCORE_DOWN = 1
SPECIAL_EVENT_MAX = 2

COLOUR_ON = 1
COLOUR_OFF = 0

KEY_LEFT = 0
KEY_RIGHT = 1
